apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-service-staging
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: oci://ghcr.io/kulkarni-abhi/helm
      chart: bugtracker-project-service
      targetRevision: 0.2.0
      helm:
        valueFiles:
          - $values/environments/staging/project-service-values.yaml

    - repoURL: https://github.com/kulkarni-abhi/bugtracker-gitops
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
