apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-dev
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/kulkarni-abhi/bugtracker-api-gateway
      targetRevision: dev
      path: helm
      helm:
        valueFiles:
          - $values/environments/dev/api-gateway-values.yaml

    - repoURL: https://github.com/kulkarni-abhi/bugtracker-gitops
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
